
name: Build the pretty version

on: [ push ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@master
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-        
    - name: Build with Maven
      run: mvn -B package -Dgwt.style=PRETTY --file pom.xml
    - name: Copy artifacts
      run: mkdir js-pretty && cp target/JsQRScanner-1.0/jsqrscanner/*.* js-pretty
    - uses: actions/upload-artifact@v1
      with:
        name: js-pretty
        path: js-pretty